name: Deploy to Firebase Hosting on PR

on: pull_request

jobs:
  test_build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies and check cache
        run: yarn install --check-cache

      - name: Check for duplicate dependencies
        run: yarn dedupe --check

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAND_WITH_UKRAINE_BC_APP }}'
          projectId: stand-with-ukraine-bc-app
